# Generated by Django 4.2.7 on 2024-01-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_alter_weatherdata_humidity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
