# Generated by Django 4.2.7 on 2024-01-19 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_defaultcity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='period_hours',
        ),
        migrations.AddField(
            model_name='subscription',
            name='period',
            field=models.CharField(choices=[('1', '1 hour'), ('3', '3 hours'), ('6', '6 hours'), ('12', '12 hours')], default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='method',
            field=models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
