# Generated by Django 4.2.7 on 2024-01-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0004_remove_subscription_period_hours_subscription_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='city',
            field=models.TextField(),
        ),
    ]
