# Generated by Django 4.2.7 on 2024-01-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0005_alter_subscription_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_notification_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
