# Generated by Django 4.2.10 on 2024-02-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0008_remove_user_jwt_token_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
